<a href="https://colab.research.google.com/github/nileshgarg-tech/mortgage-ai-document-intelligence/blob/main/Handling_JSON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Handling Json in Python
In this notebook, We are practicing how to handle json in python

In [1]:
## Importing Necessary Libraries
import json
import pandas as pd

In [9]:
## Loading the JSON Data
with open('/content/sample.json', 'r') as f:
    json_data = json.load(f)

json_data

[{'customer_id': 101,
  'name': 'Alice Johnson',
  'email': 'alice@example.com',
  'orders': [{'order_id': 5001,
    'date': '2024-02-01',
    'total': 120.5,
    'items': [{'product': 'Laptop', 'price': 1000.0, 'quantity': 1},
     {'product': 'Mouse', 'price': 20.5, 'quantity': 1}],
    'payment': {'method': 'Credit Card', 'status': 'Completed'}}]},
 {'customer_id': 102,
  'name': 'Bob Williams',
  'email': 'bob@example.com',
  'orders': [{'order_id': 5002,
    'date': '2024-02-03',
    'total': 250.0,
    'items': [{'product': 'Smartphone', 'price': 700.0, 'quantity': 1},
     {'product': 'Charger', 'price': 50.0, 'quantity': 2}],
    'payment': {'method': 'PayPal', 'status': 'Pending'}},
   {'order_id': 5003,
    'date': '2024-02-07',
    'total': 75.0,
    'items': [{'product': 'Headphones', 'price': 75.0, 'quantity': 1}],
    'payment': {'method': 'Credit Card', 'status': 'Completed'}}]}]

In [10]:
type(json_data)

list

In [11]:
orders_df = pd.json_normalize(json_data, record_path='orders')

# Display only the 'order_id' and 'total' columns
display(orders_df[['order_id', 'total']])

   order_id  total
0      5001  120.5
1      5002  250.0
2      5003   75.0

In [19]:
flat_data_df = pd.json_normalize(
    json_data,
    record_path=['orders', 'items'],
    meta=['customer_id', ['orders', 'order_id'], ['orders', 'total']]
)

flat_data_df = flat_data_df.rename(columns={'orders.order_id': 'order_id', 'orders.total': 'total'})

display(flat_data_df[['customer_id', 'order_id', 'product', 'quantity', 'total']])

  customer_id order_id     product  quantity  total
0         101     5001      Laptop         1  120.5
1         101     5001       Mouse         1  120.5
2         102     5002  Smartphone         1  250.0
3         102     5002     Charger         2  250.0
4         102     5003  Headphones         1   75.0

In [21]:
flat_data_df.to_json("items.json", orient="records")